version: 0.2

env:
  parameter-store:
    # Requires that you have a secure string in AWS Systems Manager Parameter Store
    # called "snykAuthToken" with your Snyk token.
    SNYK_TOKEN: "snykAuthToken"

phases:
  install:
    commands:
      - npm install -g snyk

  build:
    commands:
      - snyk iac test --severity-threshold=high --report --target-name=lcrowther-snyk/vulnerable_node_app || true

#artifacts:
#files:
# - location
# - location
#name: $(date +%Y-%m-%d)
#discard-paths: yes
#base-directory: location
#cache:
#paths:
# - paths